### ISSUE TITLE
Docker container here also throws error

### ISSUE THREAD

**Issue by cecs1** [CompImg/LST-AI#32]
Hi, I"m running on Ubuntu 22.
I pulled the docker container as suggested: jqmcginnis/lst-ai:latest
I then ran the following command on the data

docker run -v /home/ubuntu:/custom_apps/lst_input -v /home/ubuntu:/custom_apps/lst_output -v /home/ubuntu/:/custom_apps/lst_temp jqmcginnis/lst-ai:latest --t1 /custom_apps/lst_input/tp2-praise6-mprage.nii.gz --flair /custom_apps/lst_input/tp2-praise6-flair.nii.gz --output  /custom_apps/lst_output  --temp /custom_apps/lst_temp

It immediately crashed with:
Traceback (most recent call last):
  File "/usr/bin/lst", line 4, in <module>
    __import__('pkg_resources').require('LST-AI==1.1.0')
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3668, in <module>
    def _initialize_master_working_set() -> None:
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3651, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3680, in _initialize_master_working_set
    working_set = _declare_state('object', 'working_set', WorkingSet._build_master())
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 656, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1065, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 892, in resolve
    dist = self._resolve_dist(
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 933, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'LST-AI==1.1.0' distribution was not found and is required by the application

Any advice appreciated.
Thank you.

**Comment by jqmcginnis** [comment]
Hi @cecs1 

I am super sorry you are running into these problems; I have spent the day trying to figure out the issues and have tried some new things, which unfortunately haven't worked so far. I will keep you in the loop and let you know once I have pushed a new version to docker hub! 

Sorry for any inconvenience!

**Comment by cecs1** [comment]
Many thanks Julian!
Regards
Chris


------------------------------------
Dr Chris Steward
Dept of Radiology,
The University of Melbourne,
Royal Melbourne Hospital
Tel: +613 90356508
Email: ***@***.***
-------------------------------------
________________________________

**Comment by jqmcginnis** [comment]
Hey @cecs1 

Can you give this new docker container a try? I made quite some changes regarding CUDA, tf and pytorch versions, but I hope this one works better now :slightly_smiling_face: 

```
docker pull jqmcginnis/lst-ai:v1.2.0
```
And then run it:

```
docker run --gpus all -v /home/home/johannes_julian/lst_in:/custom_apps/lst_input -v /home/home/johannes_julian/lst_out/:/custom_apps/lst_output -v /home/home/johannes_julian/lst_temp/:/custom_apps/lst_temp jqmcginnis/lst-ai:v1.2.0 --t1 /custom_apps/lst_input/t1.nii.gz --flair /custom_apps/lst_input/flair.nii.gz --output /custom_apps/lst_output --temp /custom_apps/lst_temp
```

Would really appreciate the feedback! :slightly_smiling_face:

**Comment by cecs1** [comment]
Thanks Julian, that seemed to work. A test run took about 2 to 3 minutes on our server.
Chris


---------------------------------------------

Dr Chris Steward,

Dept of Radiology,

University of Melbourne,

Royal Melbourne Hospital

E: ***@***.******@***.***>

Ph: +613 90356508

---------------------------------------------


________________________________

**Comment by arovai** [comment]
Hello
I got the the same error as OP (using Debian 12).
Solution proposed using
```bash
docker pull jqmcginnis/lst-ai:v1.2.0
```
worked.
Would it be possible to update latest image with the changes you've made?
By the way, thanks for developing such a tool!

**Comment by jqmcginnis** [comment]
Hey @arovai 

thanks for reaching out. Do you mean pushing the `jqmcginnis/lst-ai:v1.2.0` to `jqmcginnis/lst-ai:latest`? 

Sorry if I do not understand the question correctly.

And thank you very much, really appreciate it 🙂

**Comment by arovai** [comment]
You're welcome!

Currently when pulling `lst-ai:latest` I get a version that does not work. I am thus worried that people simply reading the `README.md` will simply run into the same issue (just as I did this morning).

So either the `README.md` is changed to remove any reference to `latest` (and replace, if appropriate, with `v1.2.0`), or you tag the `v1.0.2` to be `latest` on dockerhub (or something like that - usually it is automatic if `v1.0.2` is the last push. Not sure why this is not the case if this is, indeed, the last pushed version).

I personally prefer the first of these solution, namely to explicitly mention which docker version to use, but it's a free world :-)

Best
AR

**Comment by jqmcginnis** [comment]
Ah good catch! 🙂 

I actually prefer the first one as well!
